<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SARAS-CNB01" failures="1" tests="5" name="salesforce.CreateOpportunityTest" time="115.641" errors="0" timestamp="2023-06-21T08:58:53 PDT" skipped="0">
  <testcase classname="salesforce.CreateOpportunityTest" name="case15_OpportunitiesDropDown" time="22.149"/>
  <system-out/>
  <testcase classname="salesforce.CreateOpportunityTest" name="case19_TestQuarterlySummaryReport" time="22.402"/>
  <system-out/>
  <testcase classname="salesforce.CreateOpportunityTest" name="case17_TestOpportunityFileReport" time="20.599"/>
  <system-out/>
  <testcase classname="salesforce.CreateOpportunityTest" name="case18_TestStuckOpportunityReport" time="22.674"/>
  <system-out/>
  <testcase classname="salesforce.CreateOpportunityTest" name="case16_CreateNewOpty" time="27.817">
    <failure message="Title not matched expected [Opportunity: All opportunities ~ Salesforce - Developer Edition] but found [Opportunity Edit: All opportunities ~ Salesforce - Developer Edition]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Title not matched expected [Opportunity: All opportunities ~ Salesforce - Developer Edition] but found [Opportunity Edit: All opportunities ~ Salesforce - Developer Edition]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at salesforce.SalesForceBaseTest.assertPageTitle(SalesForceBaseTest.java:155)
at salesforce.CreateOpportunityTest.case16_CreateNewOpty(CreateOpportunityTest.java:124)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- case16_CreateNewOpty -->
  <system-out/>
</testsuite> <!-- salesforce.CreateOpportunityTest -->
